version: 2.1
jobs:
  compile:
   docker:
      - image: bryanhafidz/bryan-docker:0x02
   steps:
      - run:
          command: |
           git config --global user.name "Khalif766"
           git config --global user.email "ekaristi699@gmail.com"
           git clone https://github.com/JFla-Karamel JFla
           cd JFla
           chmod a+x gettools.sh
           ./gettools.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
